# Copyright (c) 2024, 2026, Oracle and/or its affiliates.
# All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl
# spell-checker: disable

---
apiVersion: v1
kind: Namespace
metadata:
  name: "obaas-system"
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${label}
---
apiVersion: v1
kind: Secret
metadata:
  name: ${label}-signoz
  namespace: ${label}
type: Opaque
stringData:
  email: "admin@example.com"
  password: "${signoz_secret}"
---
apiVersion: v1
kind: Secret
metadata:
  name: ${label}-clickhouse
  namespace: ${label}
type: Opaque
stringData:
  username: "clickhouse_operator"
  password: "${clickhouse_secret}"
%{ if deploy_optimizer ~}
---
apiVersion: v1
kind: Secret
metadata:
  name: ${label}-optimizer-api-key
  namespace: ${label}
type: Opaque
stringData:
  apiKey: "${optimizer_api_key}"
---
# Secret containing non-privileged DB User details.
# Used for Optimizer application connectivity to database.
# User is created during cfgmgt init-containter
apiVersion: v1
kind: Secret
metadata:
  name: ${db_name}-optimizer-db-authn
  namespace: ${label}
type: Opaque
stringData:
  username: AI_OPTIMIZER
  password: "${db_password}"
  service: ${db_service}
%{ endif }
---
# Secret containing non-privileged DB User details.
# Used for OBaaS application connectivity to database.
apiVersion: v1
kind: Secret
metadata:
  name: ${db_name}-obaas-db-authn
  namespace: ${label}
type: Opaque
stringData:
  username: OBAAS_USER
  password: "${db_password}"
  service: ${db_service}
---
# Secret containing privileged DB User details.
# Used to create user defined in -db-authn in init-container
apiVersion: v1
kind: Secret
metadata:
  name: ${db_name}-db-priv-authn
  namespace: ${label}
type: Opaque
stringData:
  username: ${db_username}
  password: "${db_password}"
  service: ${db_service}
---
# Secret containing self-signed certificate; used for LB TLS
apiVersion: v1
kind: Secret
metadata:
  name: example-tls-secret
  namespace: ${label}
type: kubernetes.io/tls
data:
  ca.crt : "${ca_crt}"
  tls.crt: "${tls_crt}"
  tls.key: "${tls_key}"
%{ if use_cluster_addons ~}
---
apiVersion: "ingress.oraclecloud.com/v1beta1"
kind: IngressClassParameters
metadata:
  name: native-ic-params
  namespace: ${label}
spec:
  compartmentId: ${compartment_ocid}
  subnetId: ${lb_subnet_ocid}
  loadBalancerName: "${label}-lb"
  reservedPublicAddressId: ${lb_ip_ocid}
  isPrivate: false
  maxBandwidthMbps: ${lb_max_shape}
  minBandwidthMbps: ${lb_min_shape}
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: native-ic
  namespace: ${label}
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
    oci-native-ingress.oraclecloud.com/network-security-group-ids: ${lb_nsgs}
    oci-native-ingress.oraclecloud.com/id: ${lb_ocid}
    oci-native-ingress.oraclecloud.com/delete-protection-enabled: "true"    
spec:
  controller: oci.oraclecloud.com/native-ingress-controller
  parameters:
    scope: Namespace
    namespace: ${label}
    apiGroup: ingress.oraclecloud.com
    kind: IngressClassParameters
    name: native-ic-params
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oracle-database-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oracle-database-operator-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: oracle-database-operator-system
%{ endif }
%{ if deploy_buildkit && deploy_optimizer ~}
---
# Builds and pushes application images to container registry.
# Uses instance principles.
apiVersion: batch/v1
kind: Job
metadata:
  name: optimizer-buildkit
  namespace: ${label}
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: prepare-source-code
          image: docker.io/alpine:latest
          command:
            - sh
            - -c
            - |
              if [ "${optimizer_version}" = "Experimental" ]; then
                echo "Downloading Code from MAIN branch"
                wget -qO- https://github.com/oracle/ai-optimizer/archive/refs/heads/main.tar.gz \
                  | tar -xz -C /workspace --strip-components=1 ai-optimizer-main/src ai-optimizer-main/pyproject.toml
              else
                echo "Downloading Code from LATEST release"
                wget -qO- https://github.com/oracle/ai-optimizer/releases/latest/download/ai-optimizer-src.tar.gz \
                  | tar -xz -C /workspace
              fi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: workspace
              mountPath: /workspace
        - name: init-ocir-login
          image: ghcr.io/oracle/oci-cli:latest
          command:
            - sh
            - -c
            - |
              REPO_PATH=$(echo "${repository_base}" | cut -d'/' -f2-)

              # Fetch separate tokens for each repository
              for IMAGE in client server; do
                TOKEN_RESPONSE=$(oci raw-request \
                  --http-method GET \
                  --target-uri \
                  "https://${repository_host}/20180419/docker/token?scope=repository:$REPO_PATH/ai-optimizer-$IMAGE:push,pull&service=${repository_host}" 2>&1)
                TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.data.token')
                echo "{\"auths\":{\"${repository_host}\":{\"auth\":\"$(echo -n "BEARER_TOKEN:$TOKEN" | base64 -w0)\"}}}" > /docker-config/$IMAGE/config.json
                chown 1000:1000 /docker-config/$IMAGE/config.json
              done
          env:
            - name: OCI_CLI_AUTH
              value: oke_workload_identity
          volumeMounts:
            - name: docker-auth-client
              mountPath: /docker-config/client
            - name: docker-auth-server
              mountPath: /docker-config/server
      containers:
        - name: buildkit-client
          image: docker.io/moby/buildkit:master-rootless
          env:
            - name: BUILDKITD_FLAGS
              value: --oci-worker-no-process-sandbox --oci-worker-gc=false
          command:
            - sh
            - -c
          args:
            - |
              buildctl-daemonless.sh build \
                --no-cache \
                --progress plain \
                --frontend dockerfile.v0 \
                --local context=/workspace \
                --local dockerfile=/workspace/src/client \
                --output type=image,name=${repository_base}/ai-optimizer-client:latest,push=true
          securityContext:
            seccompProfile:
              type: Unconfined
            appArmorProfile:
              type: Unconfined
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: workspace
              mountPath: /workspace
              readOnly: true
            - name: buildkitd-client
              mountPath: /home/user/.local/share/buildkit
            - name: docker-auth-client
              mountPath: /home/user/.docker
              readOnly: true
        - name: buildkit-server
          image: docker.io/moby/buildkit:master-rootless
          env:
            - name: BUILDKITD_FLAGS
              value: --oci-worker-no-process-sandbox --oci-worker-gc=false
          command:
            - sh
            - -c
          args:
            - |
              buildctl-daemonless.sh build \
                --no-cache \
                --progress plain \
                --frontend dockerfile.v0 \
                --local context=/workspace \
                --local dockerfile=/workspace/src/server \
                --output type=image,name=${repository_base}/ai-optimizer-server:latest,push=true
          securityContext:
            seccompProfile:
              type: Unconfined
            appArmorProfile:
              type: Unconfined
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: workspace
              mountPath: /workspace
              readOnly: true
            - name: buildkitd-server
              mountPath: /home/user/.local/share/buildkit
            - name: docker-auth-server
              mountPath: /home/user/.docker
              readOnly: true
      volumes:
        - name: workspace
          emptyDir: {}
        - name: buildkitd-client
          emptyDir: {}
        - name: buildkitd-server
          emptyDir: {}
        - name: docker-auth-client
          emptyDir: {}
        - name: docker-auth-server
          emptyDir: {}
%{ endif }
