{{- if .Values.signoz.enabled }}
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: traces-instrumentation
spec:
  exporter:
    endpoint: http://{{ include "obaas.signoz.fullname" . }}-otel-collector:4318
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: always_on
{{- end }}
