apiVersion: v1
entries:
  obaas:
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2026-03-02T10:44:12.231851656-05:00"
    dependencies:
    - condition: ingress-nginx.enabled
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
      version: 4.13.2
    - condition: signoz.enabled
      name: k8s-infra
      repository: https://charts.signoz.io
      version: 0.15.0
    - condition: signoz.enabled
      name: signoz
      repository: https://charts.signoz.io
      version: 0.102.1
    - condition: apisix.enabled
      name: apisix
      repository: https://apache.github.io/apisix-helm-chart
      version: 2.12.3
    - condition: ai-optimizer.enabled
      name: ai-optimizer
      repository: https://oracle.github.io/ai-optimizer/helm
      version: '>=2.0.0 <3.0.0'
    description: A Helm chart for Oracle Backend as a Service
    digest: 38ffbf0607430701966fda5dcaff82733f1024e29e404f2cd607724d7a32997c
    home: https://oracle.github.io/microservices-backend
    kubeVersion: '>= 1.32.1'
    maintainers:
    - email: obaas_ww@oracle.com
      name: Oracle and/or its affiliates
      url: https://oracle.github.io/microservices-backend
    name: obaas
    type: application
    urls:
    - obaas-0.0.1.tgz
    version: 0.0.1
  obaas-prereqs:
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2026-03-02T10:44:12.252595329-05:00"
    dependencies:
    - condition: external-secrets.enabled
      name: external-secrets
      repository: https://charts.external-secrets.io
      version: 1.1.0
    - condition: metrics-server.enabled
      name: metrics-server
      repository: https://kubernetes-sigs.github.io/metrics-server/
      version: 3.13.0
    - condition: kube-state-metrics.enabled
      name: kube-state-metrics
      repository: https://prometheus-community.github.io/helm-charts
      version: 6.4.1
    - condition: strimzi-kafka-operator.enabled
      name: strimzi-kafka-operator
      repository: https://strimzi.io/charts/
      version: 0.45.1
    - condition: oracle-database-operator.enabled
      name: oracle-database-operator
      repository: file://charts
      version: 0.1.0
    - condition: coherence-operator.enabled
      name: coherence-operator
      repository: https://oracle.github.io/coherence-operator/charts
      version: 3.5.6
    description: Prerequisites and cluster-singleton infrastructure for Oracle Backend
      as a Service
    digest: 57be1485b888f31b16ae80d59daa427118336df524d4077bcc3d3ed6ca0c7a5a
    home: https://oracle.github.io/microservices-backend
    kubeVersion: '>= 1.32.1'
    maintainers:
    - email: obaas_ww@oracle.com
      name: Oracle and/or its affiliates
      url: https://oracle.github.io/microservices-backend
    name: obaas-prereqs
    type: application
    urls:
    - obaas-prereqs-0.0.1.tgz
    version: 0.0.1
  obaas-sample-app:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2026-03-02T10:44:12.253731185-05:00"
    description: A Helm chart for deploying applications to the Oracle Backend for
      Microservices and AI (OBaaS) Platform
    digest: 5e054d0265af986d177095005be3f95d1502b0c31f6813f552596898aa1ea8a9
    home: https://oracle.github.io/microservices-backend
    maintainers:
    - email: obaas_ww@oracle.com
      name: Oracle and/or its affiliates
      url: https://oracle.github.io/microservices-backend
    name: obaas-sample-app
    type: application
    urls:
    - obaas-sample-app-0.0.1.tgz
    version: 0.0.1
generated: "2026-03-02T10:44:12.195408636-05:00"
